# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8d8d25821c03f786e8e134c80c44985505e0262f656cc568857923289c5d4b7335c0a8db35daa679890c78004dfecf9662bcdf21447bdbbe3edadff36bb0da2

test:
  secret_key_base: 38ebe82d227bd5b05ffcc2b07b6697131a719fb676d7169ffbb64510669670d1b694c5c6dec8ce7bcd9fc29b57b1d575cd4d3edb216f0593cbc02e7c48783aeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
